In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pandas as pd

In [11]:
df = pd.read_csv(r'C:\Users\tmaal\OneDrive\Desktop\eliza project update\machine-learning-project-team-4\CoffeeDataSecUpdate.csv')

In [12]:
df.head()

Unnamed: 0  dose (g)  water temp ( C )  water vol (ml)  number of pours  \
0           0        16                93             250                3   
1           1        15                93             250                3   
2           2        14                92             240                3   
3           3        40                92             330                5   
4           4        22               100             375                3   

   TDS %  seconds  
0   1.56    165.0  
1   1.40    165.0  
2   1.25    130.0  
3   1.30    210.0  
4   1.40    140.0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        133 non-null    int64  
 1   dose (g)          133 non-null    int64  
 2   water temp ( C )  133 non-null    int64  
 3   water vol (ml)    133 non-null    int64  
 4   number of pours   133 non-null    int64  
 5   TDS %             133 non-null    float64
 6   seconds           133 non-null    float64
dtypes: float64(2), int64(5)
memory usage: 7.4 KB


#Build & Train Model¶

In [14]:
X = df[['dose (g)', 'water temp ( C )', 'water vol (ml)', 'number of pours', 'seconds']]
y = df['TDS %']

In [15]:
# Split Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.17, random_state=42)

In [54]:
regr = LinearRegression(fit_intercept=True)
lineareg_model = regr.fit(X_train, y_train)

In [55]:
import pickle

# Save the model using the correct variable name
with open('lineareg_model.pkl', 'wb') as file:
    pickle.dump(lineareg_model, file)

In [19]:
# Predict on test set
y_predict = regr.predict(X_test)

In [20]:
y_predict

array([1.51614093, 1.40026681, 1.49761205, 1.39503571, 1.52805458,
       1.41031415, 1.41713918, 1.46598226, 1.44160582, 1.48571187,
       1.41802874, 1.14643185, 1.15507722, 1.34548026, 1.46725104,
       1.62000451, 1.51015   , 1.43043635, 1.35506686, 1.48980179,
       1.43499678, 1.4646589 , 1.10149141])

In [21]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Calculate predictions on the test set
y_pred_test = regr.predict(X_test)

# Calculate metrics using the test set predictions
mae = mean_absolute_error(y_test, y_pred_test)
mse = mean_squared_error(y_test, y_pred_test)
r2 = r2_score(y_test, y_pred_test)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"R²: {r2}")

MAE: 0.1032693211902021
MSE: 0.01687320836960637
R²: 0.6111893005391922


#normalizetion MinMax

In [22]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [23]:
scaler = MinMaxScaler()

normalized_data = scaler.fit_transform(df[['TDS %']])
normalized_data

array([[0.55789474],
       [0.38947368],
       [0.23157895],
       [0.28421053],
       [0.38947368],
       [0.17894737],
       [0.21052632],
       [0.33684211],
       [0.37894737],
       [0.49473684],
       [0.6       ],
       [0.65263158],
       [0.44210526],
       [0.02105263],
       [0.37894737],
       [0.17894737],
       [0.35789474],
       [0.28421053],
       [0.        ],
       [0.22105263],
       [0.25263158],
       [0.22105263],
       [0.46315789],
       [0.6       ],
       [0.08421053],
       [0.68421053],
       [0.        ],
       [0.17894737],
       [0.15789474],
       [0.38947368],
       [0.36842105],
       [0.38947368],
       [0.32631579],
       [0.26315789],
       [0.29473684],
       [0.81052632],
       [0.49473684],
       [0.44210526],
       [0.18947368],
       [0.37894737],
       [0.67368421],
       [0.48421053],
       [0.36842105],
       [0.91578947],
       [0.72631579],
       [0.70526316],
       [0.49473684],
       [0.505

In [24]:
df['normalized_data'] = normalized_data * 100

In [25]:
df.head()

Unnamed: 0  dose (g)  water temp ( C )  water vol (ml)  number of pours  \
0           0        16                93             250                3   
1           1        15                93             250                3   
2           2        14                92             240                3   
3           3        40                92             330                5   
4           4        22               100             375                3   

   TDS %  seconds  normalized_data  
0   1.56    165.0        55.789474  
1   1.40    165.0        38.947368  
2   1.25    130.0        23.157895  
3   1.30    210.0        28.421053  
4   1.40    140.0        38.947368

In [26]:
X = df[['dose (g)', 'water temp ( C )', 'water vol (ml)', 'number of pours', 'seconds']]
y = df['normalized_data']

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.17, random_state=42)

In [28]:
regr = LinearRegression(fit_intercept=True)

In [29]:
regr.fit(X_train, y_train)

LinearRegression()

In [30]:
y_predict = regr.predict(X_test)

In [31]:
y_predict

array([51.17272924, 38.97545323, 49.2223208 , 38.42481111, 52.42679765,
       40.03306866, 40.75149222, 45.89286914, 43.32692842, 47.96967096,
       40.84513084, 12.25598372, 13.16602325, 33.20844798, 46.02642571,
       62.10573772, 50.54210496, 42.15119431, 34.21756371, 48.40018796,
       42.6312405 , 45.75356796,  7.52541139])

In [32]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Calculate predictions on the test set
y_pred_test = regr.predict(X_test)

# Calculate metrics using the test set predictions
mae = mean_absolute_error(y_test, y_pred_test)
mse = mean_squared_error(y_test, y_pred_test)
r2 = r2_score(y_test, y_pred_test)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"R²: {r2}")

MAE: 10.870454862126527
MSE: 186.9607575579651
R²: 0.6111893005391924


#Add

In [33]:
df2 =df
conditions = [
    df['TDS %'] <= 1.25,
    (df['TDS %'] >= 1.26) & (df['TDS %'] <= 1.36),
    (df['TDS %'] >= 1.37) & (df['TDS %'] <= 1.45),
    (df['TDS %'] >= 1.46) & (df['TDS %'] <= 1.52),
    df['TDS %'] > 1.52
]

choices = [0, 1, 2, 3, 4]
# ['weak', 'weak balanced', 'balanced', 'balanced strong', 'strong']

#            0        1               2              3                4
df2['status'] = np.select(conditions, choices, default='unknown')


In [34]:
df2.head()

Unnamed: 0  dose (g)  water temp ( C )  water vol (ml)  number of pours  \
0           0        16                93             250                3   
1           1        15                93             250                3   
2           2        14                92             240                3   
3           3        40                92             330                5   
4           4        22               100             375                3   

   TDS %  seconds  normalized_data status  
0   1.56    165.0        55.789474      4  
1   1.40    165.0        38.947368      2  
2   1.25    130.0        23.157895      0  
3   1.30    210.0        28.421053      1  
4   1.40    140.0        38.947368      2

In [35]:
df2['status'].unique()

array(['4', '2', '0', '1', '3'], dtype=object)

In [36]:
df2.drop(columns='normalized_data', inplace= True)

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [38]:
df

Unnamed: 0  dose (g)  water temp ( C )  water vol (ml)  number of pours  \
0             0        16                93             250                3   
1             1        15                93             250                3   
2             2        14                92             240                3   
3             3        40                92             330                5   
4             4        22               100             375                3   
..          ...       ...               ...             ...              ...   
128         128        20                92             300                4   
129         129        16                92             250                4   
130         130        16                92             250                4   
131         131        16                90             250                4   
132         132        18                92             270                4   

     TDS %  seconds status  
0     1.56    165.0      4  
1     1.40    165.0      2  
2     1.25    130.0      0  
3     1.30    210.0      1  
4     1.40    140.0      2  
..     ...      ...    ...  
128   1.52    147.0      3  
129   1.32    145.0      1  
130   1.41    148.0      2  
131   1.46    156.0      3  
132   1.37    150.0      2  

[133 rows x 8 columns]

In [39]:
X= df.drop(columns='TDS %')
y = df['status']

In [40]:
X_test,X_train,y_test,y_train = train_test_split(X,y,test_size=0.17,random_state=42)

In [41]:
model = DecisionTreeClassifier()
trained_model = model.fit(X_train,y_train)

In [42]:
import pickle

# Assuming your trained model is stored in a variable called `model`
with open('trained_model', 'wb') as file:
    pickle.dump(model, file)


In [43]:
y_pred= model.predict(X_test)
from sklearn.metrics import f1_score
f1score = f1_score(y_test,y_pred,average='macro')


In [44]:
print(f1score)

1.0
